### PR TITLE
commit for pasayatpravat 2.0

### PR DESCRIPTION
**Pull request by pasayatpravat**
Data file added

### CODE REVIEW

**Comment by Juanlu001** [comment]
From the assignment:

> **Notice that the data should not be checked out in the repository. Including data files in git repositories is considered a bad practice.**

**Comment by pasayatpravat** [comment]
I just kept the data file in the Git, but while loading the data from the file to a dataframe, I use the URL of the file (URL that points to the GitHub data file location). 
Is that what you want?

**Comment by Juanlu001** [comment]
As far as I understand, the data can be read from a URL, and `dd.read_csv` supports reading a URL. If there's any problem with that, please let me know, but having the data in git is problematic.

**Comment by pasayatpravat** [comment]
One more question to ask. Do you want the work in notebook, not in python .py file.

**Comment by Juanlu001** [comment]
No conditions on that, the easiest thing for you will be fine :)

**Pull request merged**
